chaoss/grimoirelab-tutorial

grimoireelk/a-simple-dashboard.md
Minor edit due to p2o.py not running. Installation followed the guidelines [on this page](https://jgbarah.gitbooks.io/grimoirelab-training/grimoireelk/installation.html).
=> Removing inaccurate flags in p2o.py call

before-you-start/deploying-from-dockerhub.md
docker: Invalid ip address 127:0.0.1: address 127:0.0.1:: too many colons in address.
=> Fix a typo in the ip address

mordred/the-projects-file.md
I've included some additional steps necessary to run GrimoireLab from docker locally on a Windows machine.
=> Update to Docker Deployment instructions for Windows users

cases-chaoss.md
The installation instructions link was pointing to /grimoireelk/installation.md. This was removed in the commit c5e037cb371059aa99f3b85e0d36b7a7b55775d1
The link has been updated to point to the correct section
=> Fixing broken installation instructions link

grimoireelk/a-simple-dashboard.md
The preivious markdown link was problematic. So, instead of it a http link is added. @jgbarah Its the required fix for the issue I recently reported in the grimoirelab tutorial.
I was not able to fix this using only markdown because github doesn't support opening links in new tab
[Stackoverflow](https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank)
[Github open issue](https://github.com/mojombo/github-flavored-markdown/issues/28)
=> Updated the link

perceval/scripts/perceval_gerrit_1.py, perceval/scripts/perceval_gerrit_2.py
In the current version you obtain a bug in perceval_gerrit_1.py and perceval_gerrit_2.py:
$ python3 perceval_gerrit_1.py 
Traceb:ack (most recent call last):
File "perceval_gerrit_1.py", line 13, in <module>
repo = Gerrit(url=hostname, user=user)
TypeError: __init__() got an unexpected keyword argument 'url'
This error is fixed replacing url by hostname.
=> perceval_gerrit: replace url by hostname

basics/install.md
In some cases, some non-Python packages may be needed. This patch includes some notes about that.
=> [install] Add non-Python dependencies

perceval/github.md
As discussed with @valeriocos in [the issue linked here](https://github.com/chaoss/grimoirelab-perceval/issues/483), this pull request updates the part of the tutorial which specifies a non-existing method of authentication --- using username and password.
=> Fix inconsistency between perceval tutorial and code

basics/install.md, graal/cocom.md, graal/intro.md, graal/scripts/graal_cocom_1.py, perceval/intro.md
- Added:
I haven't added it's description to `README.md` as Graal is not yet integrated to the toolchain. Let me know what you think :) 
@valeriocos @jgbarah Please do let me know if any changes required.
**Attribution**: The directory & Content structure is inspired from Perceval's tutorial in order to maintain consistency.
**REF #75**
Thanks
=> [graal] Add Graal to GrimoireLab Tutorial

sortinghat/data.md
Updated the mysql -u user -pXXX -e 'SELECT * FROM identities;' shdb
command to mysql -u user -pXXX -e 'SELECT * FROM uidentities;' shdb
as there was a typo in table name.
=> typo in tables name

_data/sidebars/home_sidebar.yml, sirmordred/micro-mordred.md
@valeriocos @jgbarah Please do let me know if any section needs more elaboration :)
Fixes: #84 
Signed-off-by: inishchith <inishchith@gmail.com>
=> [micro-mordred] Add tutorial for exectution of Micro-Mordred via

sirmordred/micro-mordred.md
The [micro-mordred example](https://chaoss.github.io/grimoirelab-tutorial/sirmordred/micro-mordred.html) includes a command that the user is expected to execute but which is missing the `--cfg` flag.  Without this, they get the following error:
```
usage: micro.py [--arthur] [--raw] [--enrich] [--identities-load]
[--identities-merge] [--panels] [--cfg CFG_PATH]
[--backends [BACKEND_SECTIONS [BACKEND_SECTIONS ...]]]
micro.py: error: unrecognized arguments: setup.cfg
```
This PR adds the missing flag.
=> Add missing --cfg flag to example micro-mordred command

basics/supporting.md
As a new user and a technical end-user rather than a developer, these instructions were unclear to me that Elasticsearch was not being installed as part of the installation process. Made a small suggestion for making this explicitly clear based on my understanding of the situation.
Signed-off-by: Ruth Cheesley <ruth.cheesley@acquia.com>
=> Clarity on Elasticsearch requirement

README.md
The Eclipse dashboard is no longer online, so we move to another one.
The screenshot should be updated at some point, but maybe that's not that important now.
=> Change Eclipse dashboard for OPNFV dashboard

basics/quick.md
Fix the broken link in the [installation-for-the-impatient](https://chaoss.github.io/grimoirelab-tutorial/basics/quick.html)  page.
Signed-off-by: LinHaiming <lhming23@outlook.com>
=> Fix the broken link in the installation-for-the-impatient page

_data/sidebars/home_sidebar.yml
The Presentation page contains the same content as the
Introduction page, hereby causing unnecessary duplication.
This commit corrects that by removing the Presentation page
from the sidebar.
References: #134
=> Removes duplication from the sidebar

docs/data-sources/configurations.md
This commit adds documentation for using grimoirelab against
private git repositories. The configurations.md is updated
with an example.
Signed-off-by: Jorge García Rey <jorgegar@inditex.com>
=> [docs] Add information for using private git repos

_config.yml
Fixes #195
There was an issue with the [_config.yml](https://github.com/chaoss/grimoirelab-tutorial/blob/master/_config.yml) file that was generating a link to the [tesseract](https://github.com/chaoss/grimoirelab-tutorial/tree/tesseract) branch instead of the intended [master](https://github.com/chaoss/grimoirelab-tutorial/tree/master) branch.
=> [config] Updated the link in the footer to master

docs/data-sources/configurations.md
Seemed easier to correct than report. Unclear if I have followed the rules though (did not notice the sign-off requirement initially).
Signed-off-by: Michael Alexander <malexander@mgalexander.com>
=> Fix typo in schema for github https:/ vs https:// in examples.

docs/components/workflow.md
1. fixes issue #204, use three new links in `/components/workflow.md`
2. fills one alt text with `grimoirelab-all-complete.png` instead of leaving it empty.
3. Replace ul-style back.
The first commit also replaced the ul-style from asterisk to dash accidentally, to make the style consistent I change it back later.
The second commit is irrelevant but good for markdown format, I'd like to keep it in this PR.   
Fixes #204
=> Fix invalid URLs

CONTRIBUTING.md, basics/dockerhub.md, basics/install.md, basics/quick.md, basics/supporting.md, cases-chaoss/intro.md, docs/data-sources/add-configurations.md, docs/getting-started/dev-setup.md, docs/getting-started/setup.md, docs/getting-started/troubleshooting.md, gelk/kidash.md, gelk/meetup.md, gelk/simple.md, gelk/sortinghat.md, graal/cocom.md, manuscripts/first.md, python/es-dsl.md, python/es.md, sirmordred/container.md, sirmordred/micro-mordred.md, sortinghat/basic.md, sortinghat/data.md, tools-and-tips/csv-from-jenkins-enriched-index.md, tools-and-tips/elasticsearch.md, tools-and-tips/html5-app-latest-activity.md, tools-and-tips/perceval.md
Remove `$` in every command shell
Closes #214
=> fix: remove dollar sign on command shells

docs/data-sources/add-configurations.md, docs/data-sources/configurations.md
This commit updates the cfg configs by commenting the optional/suggested configs in the example configurations.
#203
=> Add suggestions as comments for cfg configurations

Gemfile
Versions bumped automatically with `bundle update`.
webrick was added to support Jekyll versions 3.0.0 or later.
=> Bump dependencies versions
