grimoireelk/a-simple-dashboard.md
grimoireelk/installation.md
python/elasticsearch-dsl.md
python/querying-grimoireelk-indexes.md

This is a minor commit, really. Typos only.

Fix minor typos.

---

grimoirelab/intro/scenarios.md

Fixed a bunch of typos I found while reading through the documentation.

Fixed typos

---

LICENSE.md
_config.yml
_data/sidebars/home_sidebar.yml
_includes/footer.html

Add licenses in footers.
Change license attribution to GrimoireLab.
Minor changes to _config.yml to properly show license.

Add license properly in footers.

---

python/elasticsearch.md
python/scripts/cleanup.py

This script is an example of how to use the elasticsearch Python package to delete and check for indexes.

Add cleanup.py script.

---

_includes/footer.html

Fix "Edit me" link

---

basics/install.md
basics/scenarios.md
perceval/git.md

Found a markdown syntax error and a few other typos on the grimoire-lab tutorial website.

fix a couple of typos and markdown syntax errors

---

gelk/sortinghat.md
sirmordred/projects.md

Found a typo and an older link

Fix link to perceval readme file

---

manuscripts/first.md

@jgbarah Please check this out and see if this note should be added or not

Add note for pdflatex

---

perceval/github.md

This is in reference to the issue [here](https://github.com/chaoss/grimoirelab-perceval/issues/494)
Discussion about this is done in this [PR ](https://github.com/chaoss/grimoirelab-perceval/pull/495)
The information about cartegories returned by Perceval is not mentioned.
Note added: Every Pull Request is Issue , but not every issue is a pull request

 Update info about categories returned by Perceval

---

sirmordred/dashboard.md

I think  the command mordred -c mordred-simple.cfg should be replaced with mordred -c sirmordred-simple.cfg.

updated sirmordred command

---

contributing.md

Letting contributors know about DCO and sign-off

[contributing.md] Section about DCO and sign-off

---

_data/sidebars/home_sidebar.yml

This adds Graal tutorial to the sidebar ( which wasn't added earlier )
@jgbarah @valeriocos Please have a look :)
REF: #76 
Signed-off-by: inishchith <inishchith@gmail.com>

 [graal] Add Graal to the Sidebar

---

_data/sidebars/home_sidebar.yml
internals/testing-with-httpretty.md

This closes #81 . Please have a look @jgbarah @valeriocos!

[internals] Add testing-with-httpretty internals doc

---

basics/supporting.md

Signed-off-by: Ruth Cheesley <ruth.cheesley@acquia.com>

Fix broken image link

---

basics/supporting.md

I also took the opportunity to fix some bad uppercasing of Elasticsearch.
This addresses the comment by @valeriocos in #99.

Update versions of Elasticsearch and Kibiter/Kibana

---

basics/install.md
basics/quick.md

Fixes #45.
@jgbarah @valeriocos, please let me know if you have any suggestions.

added reference links for non-python packages at required places

---

gelk/sortinghat.md

Signed-off-by: Ruth Cheesley <ruth.cheesley@acquia.com>

Minor typo

---

gelk/meetup.md

Based on working through this today, adding some more detailed information on how to generate the API token required for meetup.com integration.
Signed-off-by: Ruth Cheesley <ruth.cheesley@acquia.com>

Add detail on how to generate the Meetup API token

---

README.md
gelk/intro.md
gelk/kidash.md
gelk/meetup.md
gelk/sortinghat.md
sirmordred/container.md
sirmordred/dashboard.md
sirmordred/micro-mordred.md
sortinghat/basic.md
sortinghat/data.md

I was going through the sirmordred tutorials and found some typos. Please let me know if there are any more changes to do. :slightly_smiling_face: 
Signed-off-by: Venu Vardhan Reddy Tekula <venuvardhanreddytekula8@gmail.com>

fix minor typos and broken links in the tutorials

---

sirmordred/dashboard.md
sirmordred/files/mordred-simple.cfg

Signed-off-by: abhiandthetruth <abhiandthetruth@gmail.com>

removed 'bots_names' param from sample config

---

cases-chaoss/activity.md
gelk/kidash.md
gelk/simple.md
gelk/sortinghat.md
tools-and-tips/elasticsearch.md

Signed-off-by: abhiandthetruth <abhiandthetruth@gmail.com>
Also fixed a spotted spelling mistake ;)

changed --elastic_url-enrich to --elastic_url

---

sirmordred/micro-mordred.md

Fixed kibiter version in tutorial to match the version in README.md

fixed kibiter version for docker-config.yml

---

python/es.md
sirmordred/files/mordred-simple.cfg

This commit adds kibiter_url to mordred config file.
This aligns it with the tutorial
A small typo is also fixed.
Signed-off-by: animesh <animuz111@gmail.com>

[sirmordred] Align config file with tutorial

---

sirmordred/micro-mordred.md

Fix broken link to setup.cfg in micro-mordred.md

---

sirmordred/micro-mordred.md

Signed-off-by: abhiandthetruth <abhiandthetruth@gmail.com>
Linked to issue 
https://github.com/chaoss/grimoirelab-sirmordred/issues/433

Fixed a link to sirmordred readme

---

sirmordred/projects.md

Signed-off-by: Eva Millán <evamillan@bitergia.com>

Update repository URLs on projects file example

---

cases-chaoss/activity.md

Fixes invalid link to chaoss_community_activity.json on /cases-chaoss/activity.md
Signed-off-by: Eva Millán <evamillan@bitergia.com>

Fix broken link in Cases: CHAOSS Metrics

---

python/querying.md

Signed-off-by: Wasim Akhtar Khan <wasimkhan03150@gmail.com>

Fixed Typo Error

---

docs/community-health/code-dev-activity.md
docs/community-health/code-dev-efficiency.md
docs/community-health/contributions.md
docs/community-health/index.md
docs/community-health/issue-resolution.md
docs/community-health/people.md
docs/community-health/time.md

This commit adds the initial files related to the
community health sections. Each section will be created
as another directory with its own assets within community-health.
Signed-off-by: sevagenv <sevagenv@gmail.com>

[docs] Add community health section

---

docs/data-sources/configurations.md

Document the optional parameter for project filtering in configuration of jira data source.

Add optional project filtering for jira

---

Gemfile.lock
docs/getting-started/dev-setup.md
docs/getting-started/troubleshooting.md

Signed-off-by: Sukriti-sood <soodsukriti1111@gmail.com>
Fixes #183

port the developer installation

---

docs/getting-started/troubleshooting.md

Add `Directory Not Found` error case.
This is ported from
https://github.com/chaoss/grimoirelab-sirmordred/pull/542
Signed-off-by: TieWay59 <tieway59@foxmail.com>

[docs] update troubleshooting

---

docs/getting-started/dev-setup.md
docs/getting-started/troubleshooting.md

This PR fixes some formatting issues and also updates the content in the dev-setup and troubleshooting sections.

Update content and fix formatting issues

---

docs/getting-started/dev-setup.md
docs/getting-started/troubleshooting.md

Signed-off-by: Venu Vardhan Reddy Tekula <venu@chaoss.community>

Add language tag for code blocks

---

LICENSE
_config.yml

Updated footer and license copyright year to be 2017-2022. This will need changing in a few weeks too.

Update copyright year to current year

---

docs/getting-started/dev-setup.md
docs/getting-started/troubleshooting.md

This shows up early in the tutorial, so I was legitimately unsure if the correct spelling was mordred or modred

Fix modred / mordred typo
